[package]
name = "pizza-analysis-spanish"
version = "0.1.0"
authors = ["INFINI Labs <hello@infini.ltd>"]
edition = "2021"
license = "MIT"
description = "Spanish text analysis plugin for INFINI Pizza"
repository = "https://pizza.rs"
keywords = ["pizza", "spanish", "stemmer", "nlp"]

[features]
default = []
std = ["pizza-engine/std", "once_cell/std", "pizza-analysis-core/std"]

[dependencies]
pizza-engine = { path = "../../lib/engine", default-features = false }
pizza-analysis-core = { path = "../analysis-core", default-features = false, features = ["std"] }
hashbrown = { version = "0.14", default-features = false }
once_cell = { version = "1", default-features = false, features = ["alloc"] }

[workspace]

[dev-dependencies]
